### ISSUE TITLE
console_redirect_start.sh seems not working

### ISSUE THREAD

**Issue by tt1k** [luoqisheng/ConsoleRedirect#3]
Hi there, I think this is really an interesting project! As I try to run this, problems has been seem.

$HOME/ConsoleRedirect folder is generated but no console.log file found as Xcode project running.

It seems to be the console_redirect_start.sh not working.

Thanks.

<img width="830" alt="Screenshot 2022-08-26 at 14 45 22" src="https://user-images.githubusercontent.com/46364143/186840071-7773acba-10a6-4551-b44e-d8406d8a9585.png">

**Comment by luoqisheng** [comment]
if you use an intel machine, try 1.0.4.    Please make sure that only 1 USB device is connected. Multiple device connections are currently not supported

**Comment by luoqisheng** [comment]
you should  add run script in running phase not testing phase

**Comment by tt1k** [comment]
Thanks for looking into it!

Still not working as adding run script in phase "Generates output", also phase "Starts" not working.

BTW, this is M1 mbp and Xcode 13.4.1, only one iPhone device connected.

<img width="830" alt="Screenshot 2022-08-26 at 21 15 02" src="https://user-images.githubusercontent.com/46364143/186911861-ca258ac6-03af-4572-962c-651458f9c8db.png">

**Comment by luoqisheng** [comment]
<img width="661" alt="image" src="https://user-images.githubusercontent.com/5061690/187010577-95783cba-5a56-4c32-8be0-460d52b8bdd4.png">
Have you authorized ConsoleRedirectOSX to access the folder？Can't find the console.log file, or is the content of the console.log file empty.

**Comment by tt1k** [comment]
It works now! Thank you!
